### ISSUE TITLE
Not able to see recipes for burneable items

### ISSUE THREAD

**Issue by bell07** [minetest-mods/craftguide#40]
I am not able to get the recipe "tree" -> "wood". If I search for tree I get only the recipe the tree is burneable. The button "Recipe x / y" is not shown.

If I search for "wood" at the first, I see the recipe. But if I click to tree, the issue appears again.

Edit: By the way, I do not see the recipe the wood is burneable ...

**Comment by pauloue** [comment]
Not being able to see tree->wood when you search for tree is normal; you can search for recipes, not usages (recipe=the item is the output, usage=the item is an input). For example you can't see the key->gold ingot recipe when you search for key.

For all burnable items there is a tooltip to show the burntime. This is how you see that wood is burnable. The reason why the display is different for some items (tree, leaves, etc) is that these items have no recipe, so you can't search for them to see the tooltip.

This display is a bit of an inconsistency because it is showing the selected item as an input, not output. To solve this I have an idea to add a toggle button to switch between "recipes" and "fuels". When it's showing recipes it would not show items that are not craftable (tree, leaf, saplings, etc). When you switch to fuel display it would show all burnable items it order of burntime, with burntime tooltips. @kilbith what do you think? I'll make a demo.

**Comment by bell07** [comment]
Maybe it is more intuitive to have 2x buttons for recipes and usages at the same time? Then if searching for tree, there are no recipes but usages. Currently I cannot switch to the usages view because the buring icon is not klickeable. 
In case of search for "wood" both buttons are visible as "Recipes 1/4" and "Usage 1/4" so the player can decide what he like to see at next.

**Comment by pauloue** [comment]
Not sure exactly what you mean, but it wouldn't make sense to to have both a "recipe" and "usage" button displayed at the same time because the recipe displayed will either be a recipe for the selected item or a usage, not both. 

Another option could be to have a global toggle button to switch between showing recipes/usages. I might try that too.

**Comment by kilbith** [comment]
Not worth cluttering the formspec with a new button. Simplicity is intuitiveness.
