### ISSUE TITLE
Show replacements and repairing recipes

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/craftguide#48]
In order to make the [wiki table](https://wiki.minetest.net/Crafting_guide) fully green on the `craftguide` row, this is now possible to show the `replacements` and `repairing` recipes. These "recipes" need to be collected manually and registered as custom recipes.

BTW, @Wuzzy2, this wiki page needs an update (`sfinv` integration, `/craft` command, custom recipes API).

**Comment by pauloue** [comment]
Recipes with replacements are already shown, the replacement is just not indicated. This can be done be adding an "R" label to the item that gets replaced and indicating in the tooltip what the replacement is. For example for the lava bucket fuel recipe, the tooltip would say "Replaced with _Empty Bucket_ on crafting".

As for `toolrepair` recipes, I think the solution is for Wuzzy to drop that column from the table :)
A game has only one `toolrepair` recipe, usually defined `minetest.register_craft({type="toolrepair", additional_wear=-0.02,})`, which applies to all tools. So this is more of a game feature than a recipe. The recipe does not apply to tools with the `disable_repair` group, but this group will most likely be used for tools that it wouldn't make sense to repair. It wouldn't make sense to show a tooltip saying "this item cannot be repaired" for those items, since this the expectation.

**Comment by Wuzzy2** [comment]
Repairing is still a recipe, as you use the crafting grid for this. The `toolrepair` thing is just a weird notation which actually registers multiple shapeless recipes (one per tool). So it is completely reasonable to have it in a crafting guide. The column will not be removed.
MineClone 2 actually supports repairing recipes. MineClone 2 is using a `craftguide` fork (as `mcl_craftguide`), by the way. I was just too lazy to backport it.

The implementation is simple:
Those recipes just show up as ordinary shapeless recipes in the crafting guide (one per tool), and the output item has a little note / tooltip on it. Items with `disable_repair=1` are simply skipped (not in repository yet).

By the way: I am not the only one who can edit the wiki … Just saying. Just get yourselves an account, already! :P

**Comment by Wuzzy2** [comment]
Oh right, I totally forgot that this was basically just an ugly hack which I did …
Now I also remember why I didn't propose this before. :D
Sadly `get_all_craft_recipes` doesn't return `toolrepair`.
Nevermind.

The Minetest Wiki is not Wikipedia, it does not have to be perfectly neutral all the time. As long you're not bullshitting the wiki, it should be fine, I guess.

**Comment by kilbith** [comment]
Victory: https://github.com/minetest-mods/craftguide/commit/94f2baa857d

**Comment by kilbith** [comment]
And win: https://github.com/minetest-mods/craftguide/commit/1d1560f6a580ec94336702e3078673eda771d9cc

**Comment by Wuzzy2** [comment]
Replacements: Mostly OK.

Repair: No, this is now how it is supposed to work.
Repairable tools don't get any special UI changes. Only the *unrepairable* tools do. But just looking at `disable_repair` is wrong, too. If the game does not have the repairing recipe, then *all* tools are unrepairable, but the mod will only show those with the group.

The requirements for fulfilling Repair is as follows:

* Display which tools can be repaired using the repair recipe
* Ideally, show the repair recipe as a shapeless recipe for each repairable tool (because that's what the repair recipe basically is)
* Optional: Display the repair %

Since it is impossible to detect whether the special repair recipe has been registered so far, it's impossible to implement right now. Simply guessing the setting will lead to an incorrect result. Needs engine change. :(

And yes, I totally think it's a bug that we can't get the repair recipe right now. :(

**Comment by kilbith** [comment]
OK I will do it the other way around for repairable tools and display the repair %. I'm against adding a shapeless recipe for each tool, though.

**Comment by Wuzzy2** [comment]
Lol, by overwriting minetest.register_craft, right? >_>

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/dee585c7de8b406ac5a84e4be7c268ca296934d3

**Comment by Wuzzy2** [comment]
How about adding a *single* shapeless recipe that has a “generic” tool icon and the tooltip “A repairable tool” and the result saying “Repaired tool (X%)?

**Comment by kilbith** [comment]
That's also a good idea but the user may not notice this recipe at first in the crowd of items, whilst he has more chances to notice this property per tool.

I guess the wiki row can be turned back full green now? :)

**Comment by Wuzzy2** [comment]
That tooltip is not really discoverable either.

But your mod now *technically* fulfils the requirement. Not really in a good way, but it does.

Why not use both? Tooltip and new item entry?

**Comment by kilbith** [comment]
If I get a nice icon representing a generic tool, maybe ;)
