### ISSUE TITLE
Progressive list update does not work as expected without pages change

### ISSUE THREAD

**Issue by bell07** [minetest-mods/craftguide#50]
Steps to reproduce:

1. Start with progressive mode and minetest game
2. Drop aspen tree nearly to player and get jungle tree to inventory
3. Look to the crafting guide => You get the jungle wood recipe as expected
4. Collect aspen tree without changing sfinv pages (shortly leave inventory, collect and start back)
5. Issue: There is no way to refresh the prorgessive selection for changed items, except changing the sfinv pages

Please also note the progressive selection should be refresheable in case of active search using search button

**Comment by kilbith** [comment]
Using a button to actualize is not the best approach. Instead the engine should have a callback when the inventory is opened. @rubenwardy maybe?

**Comment by pauloue** [comment]
Since the inventory is client-side that would probably have to wait until we get server sent client mods.

Maybe the ideal solution would be to update the progressive items when a new item type is added to the inventory or the last item of some type is removed from the inventory. We would need a new callback for this too, like `on_player_inventory_action`, but it needs to be called for any addition/removal, not just when the player adds/removes an item from their inventory.

**Comment by kilbith** [comment]
Fixed by https://github.com/minetest-mods/craftguide/commit/59b806c9c494b98f0f67015afa4978f75d17b309
