### ISSUE TITLE
Digging recipe added for stone → cobblestone, but not for anything else

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/craftguide#63]
There is a digging recipe for stone → cobblestone, but the craftguide ignores digging results for anything else. This does not make sense.

Either the craftguide should show all digging results, or none of them. Anything “in between” is inconsequent and weird.

**Comment by kilbith** [comment]
Without surprise, this is a [custom recipe](https://github.com/minetest-mods/craftguide/blob/master/init.lua#L102-L107). Such recipes have to be collected manually.

**Comment by pauloue** [comment]
I don't think "digging" recipes make sense. Registered recipes should only involve items in a player's inventory. If "digging" is a valid crafting type, then e.g. monster--killing-->loot must be a valid recipe. Also if interacting with the world counts as a craft, then progressive mode doesn't make sense with these recipes since you don't need them in your inventory.

A better example of a custom craft type would be e.g. brewing or alloying.

**Comment by kilbith** [comment]
To be fair, this recipe was registered as a demo over all.

**Comment by Wuzzy2** [comment]
I suggest to remove this “demo” (your own words) then and to put it as an example in the API docs somehow.

It should be up to mods and games to decide whether they consider “digging” a crafting recipe or not. I agree with paulone.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/craftguide/commit/1f6de2a04f4de37e64ab17c9d418950fd911f93f
