### ISSUE TITLE
Use the builtin engine translator instead of intllib?

### ISSUE THREAD

**Issue by kilbith** [minetest-mods/craftguide#66]
What are the pros and cons to using the former versus `intllib`?
Is the engine translator mature enough?

@Wuzzy2 @Ekdohibs

**Comment by Wuzzy2** [comment]
I love your pessimism, because it's justified.

OK, now for the facts:

Pros:
- Part of the Lua API, no more dependency hell!
- Part of the engine, therefore by default available for all players
- Unlike `intllib`, does not force a single language on all users, making it work properly on servers

Contras:
- There's real no toolchain for basic tasks like “updating strings”. We would have to write one ourselves. There are some unfinished scripts flying around somewhere, I would have to dig them out first …
- Uses its own weird translation file format instead of Gettext PO files (OF COURSE!)
- Because of weird translation file format, we can forget uploading to Weblate. You didn't use it so far anyway, but still!
- Does not support numerus, unlike PO (irrelevant for `craftguide`)
- The core devs did not adopt it in MTG after 1.5 years of its introduction. But screw MTG, am I right?

My recommendation:
Adopt engine translator, despite its flaws. The fact that it can be used properly on servers is still a major improvement over `intllib`. Devs agree that it sucks its not PO.

**Comment by Ekdohibs** [comment]
I'll just add that making the engine support po files is planned - but I don't know yet when I will have the time and energy to implement it.

**Comment by kilbith** [comment]
[Bye-bye intllib](https://github.com/minetest-mods/craftguide/commit/8f6f8dda7e07ceb1a8b751de2efada929c0de362). The translation files need to be renewed though.
